### ISSUE TITLE
Typescript compatibility?

### ISSUE THREAD

**Issue by JulienDemarque** [kevtiq/digl#1]
Hello! thanks for this awesome-looking package, just one question, it seems to be written in typescript, yet when I import it, it complains of missing type declaration... any plan to fix that?

**Comment by JulienDemarque** [comment]
ah nevermind, I copied the import from the github readme and there is a typo (` instead of '):
<img width="724" alt="Screen Shot 2021-08-23 at 15 06 29" src="https://user-images.githubusercontent.com/27313954/130444418-94e2d904-103d-450c-8c76-c9a8c993d20f.png">

**Comment by thecrinkles** [comment]
Lol, oh my god. That's a poor mistake from my end, but fixed it in the Readme. Thanks!
