### ISSUE TITLE
The positioning step should not be part of the algorithm 

### ISSUE THREAD

**Issue by thecrinkles** [kevtiq/digl#10]
The positioning step should not be part of the algorithm. It is not flexible (as it assumes fixed sized nodes) and has nothing to do in determining the various ranks. This step should be removed from the package, or should be a separate function that can be called.

**Comment by wlievens** [comment]
I agree. I only use the ranking and then determine my own positioning, so it would be easier if the functionalities were split, with a common facade function.

**Comment by thecrinkles** [comment]
This is removed in the v1.0.0 release.
