### ISSUE TITLE
Example positioning algorithm with flexible node sizes

### ISSUE THREAD

**Issue by tomaszferens** [kevtiq/digl#13]
The positioning algorithm referenced in README handles only fixed sized nodes.

I mean this one:
```ts
export default function positioning(
  config: Config,
  nodes: Node[],
  ranks: Rank[]
): Layout {
  const _nodes: PositionedNode[] = [];
  const _h = config.orientation === 'horizontal';

  ranks.forEach((r, i) => {
    const xStart = _h
      ? 2 * config.width * i
      : -0.5 * (r.length - 1) * 2 * config.width;
    const yStart = _h
      ? -0.5 * (r.length - 1) * 2 * config.height
      : 2 * config.height * i;

    r.forEach((nodeId, nIndex) => {
      const _node: Node = nodes.find((n) => n.id == nodeId) as Node;
      if (!_node) return;
      const x = _h ? xStart : xStart + 2 * config.width * nIndex;
      const y = _h ? yStart + 2 * config.height * nIndex : yStart;
      _nodes.push({ ..._node, x, y });
    });
  });

  return _nodes;
}
```

How to position nodes with flexible sizes? Do you have any ideas how to achieve that?

**Comment by thecrinkles** [comment]
That is a tough one. It depends on a few factors I believe:

- Do you know any pointers towards the size prior to rendering? 
- What type of framework are you using. 

One type of solution would be to render everything in 2 steps: first draw all the nodes (e.g. on the same spot) so you can determine the size of each of the nodes. Once you deduced the size of the nodes, you can redraw them in the correct position. 

Another solution would be using a force algorithm to automatically determine the placement of all the nodes automatically. This would again be in 2 stages. Between nodes winching a rank, and between ranks. Unfortunately I don't have one laying around.
