### ISSUE TITLE
support for variant?

### ISSUE THREAD

**Issue by JulienDemarque** [kevtiq/digl#2]
I am testing this library for my use-case, but in some instances it doesn't look right:
<img width="380" alt="Screen Shot 2021-08-31 at 1 22 26" src="https://user-images.githubusercontent.com/27313954/131413563-46d8dfcf-c82b-4120-b0f4-26cea2d56f8f.png">
What I would want is to never have path going horizontal or going up, it should all flow down. Any idea how I could achieve this?

**Comment by thecrinkles** [comment]
First of all, looks awesome!

Secondly, is there an actual edge between 'Upload CSV' and 'End IF Step'. If so, would your preference be that 'end if step' would be placed lower than 'Upload CSV'?

**Comment by JulienDemarque** [comment]
> First of all, looks awesome!

Thanks!

> Secondly, is there an actual edge between 'Upload CSV' and 'End IF Step'. If so, would your preference be that 'end if step' would be placed lower than 'Upload CSV'?

yes exactly. the thing is that if  'Condition', 'Upload CSV', 'End IF Step', and 'EndProcess' are all on a different Rank, I suppose they would be on a vertical line, which would look also broken. 
I am thinking i may be able to hack it by checking if a node has a path coming to it from the same rank or below, if so, then push down (position Y) this node and all nodes branching down from it without changing the X position.
This is a hack because the rank would be meaningless, unless adding empty spots in a Rank array...

**Comment by thecrinkles** [comment]
I think it would be possible to create this in. It is a combination of two optional points that should be added to the graph. 

- Adding an optional flag to disallow edges within a rank, or edges that go back to a previous rank. If this case is found, the ranks will be adjusted. As said you will push nodes to other ranks (and create new ranks). This will happen recursively until the graph complies with the rules if this flag. 
- In addition, another optional flag should be added to disallow loops in the graph. (created an issue for this one already #3 )

Both seem to be good ones to add. Of course the first one could result a very vertical or horizonal graph, but it would be an optional flag. I do see the value of both flags for complex graphs as well, especially when you have a lot of information attached to an edge. Edges within a rank would be provide a horrible experience.

**Comment by JulienDemarque** [comment]
> Adding an optional flag to disallow edges within a rank, or edges that go back to a previous rank. If this case is found, the ranks will be adjusted. As said you will push nodes to other ranks (and create new ranks). This will happen recursively until the graph complies with the rules if this flag.

Yes should be possible, the tricky bit is that it would require to have "holes", empty spots that would make the graph asymmetric.
For example what i am trying to achieve:
<img width="264" alt="Screen Shot 2021-08-31 at 17 46 05" src="https://user-images.githubusercontent.com/27313954/131524369-aeb37a8a-e4de-4c05-ab10-87cc780bc149.png">

As you can see the Instructions Node in not centered in the middle of the graph...

**Comment by thecrinkles** [comment]
Hmmm interesting. 

The first two steps would still be the ones I described. But, indeed, some additional steps with adding empty ranks should be be added. That part I have to think about how to achieve that.

**Comment by JulienDemarque** [comment]
I was thinking of a completely different approach. By changing the very first thing the algo does:

> Use a breadth-first search algorithm to determine the shortest possible route from the start node. The length of the found shortest route for each node is used as the corresponding rank of the node.

to 

Use a breadth-first search algorithm to determine the **longest** possible route from the start node. The length of the found **longest** route for each node is used as the corresponding rank of the node.

Maybe this way there would be no upward or horizontal paths... There is still the problem of the empty spots to add, still thinking about it, but I guess it should happen only when a path jumps more than 1 rank, then all intermediate ranks should be added empty spots to make some space...

**Comment by JulienDemarque** [comment]
@crinklesio I copied your lib and made the above adjustments. If you want I can make a PR to your repo so you can take a look... 
I haven't fully QA but it is better already for my use case.

**Comment by thecrinkles** [comment]
@JulienDemarque that would be very interesting. I have yet to find the time to look at it myself.

**Comment by JulienDemarque** [comment]
@crinklesio Ah i don't have permission to push to the repo, if you can add me for permissions (except main), I can push my branch

**Comment by thecrinkles** [comment]
> @crinklesio Ah i don't have permission to push to the repo, if you can add me for permissions (except main), I can push my branch

Should be possible now.

**Comment by JulienDemarque** [comment]
@crinklesio here is the PR: https://github.com/crinklesio/digl/pull/5

**Comment by thecrinkles** [comment]
@JulienDemarque apologies for the late reply. 
I will look at the PR somewhere this or next week. I was thinking though, your proposed approach of starting with the 'longest path from the start' might be a better approach right from the start. That would mean it becomes the default option (and possible the only one).

**Comment by JulienDemarque** [comment]
@crinklesio No worry, I had to switch to a different library. I am using Dagre at the moment, it gives me the position of edges so they can go around nodes. but it still doesn't really fulfill my needs, because I can have multiple edges between 2 nodes, and this is not supported, so I had to do some workaround.
I saw elk (https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-layered.html) supports multi-edges but I could never make it work... I wish someone would have extracted their lib into a proper typescript package.

**Comment by thecrinkles** [comment]
#6 changes the default to 'longest path from source' for the initial ranking of nodes, instead of shortest path from source. I believe it is the better approach, as it will result in better layouts. 

Adding empty spots based on your PR (#5 ) is the next step.
