### ISSUE TITLE
Solitary nodes

### ISSUE THREAD

**Issue by wlievens** [kevtiq/digl#8]
I'm trying to use DIGL for a project. What I'd like to do is mark a node as "solitary", meaning that it will be alone in its rank. Every other node would be scheduled either on a lower, or on a higher rank. I want to do this for particularly "large" nodes (in terms of visualization), to avoid overlapping other node boxes in the layout. Would it possible to add this kind of constraint?

**Comment by thecrinkles** [comment]
Your changes looked good, published them just now in version 0.5.0. Should be on NPM in a moment.

**Comment by wlievens** [comment]
Thanks!
